---
### Python 2.7
kind: pipeline
name: Python 2.7

steps:
- name: test
  image: registry.dinotools.org/docker-ci/python:2.7
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev libfuzzy-dev
  - . /opt/python/venv/bin/activate
  - python --version
  - pip install tox
  - BUILD_LIB=0 tox --recreate -vvv -e py27

---
### Python 3.5
kind: pipeline
name: Python 3.5

steps:
- name: test
  image: registry.dinotools.org/docker-ci/python:3.5
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev libfuzzy-dev
  - . /opt/python/venv/bin/activate
  - python --version
  - pip install tox
  - BUILD_LIB=0 tox --recreate -vvv -e py35

---
### Python 3.6
kind: pipeline
name: Python 3.6

steps:
- name: test
  image: registry.dinotools.org/docker-ci/python:3.6
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev libfuzzy-dev
  - . /opt/python/venv/bin/activate
  - python --version
  - pip install tox
  - BUILD_LIB=0 tox --recreate -vvv -e py36

---
### Python 3.7
kind: pipeline
name: Python 3.7

steps:
- name: test
  image: registry.dinotools.org/docker-ci/python:3.7
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev libfuzzy-dev
  - . /opt/python/venv/bin/activate
  - python --version
  - pip install tox
  - BUILD_LIB=0 tox --recreate -vvv -e py37

---
### Python 3.7
kind: pipeline
name: Python 3.7 - Docs

steps:
- name: sphinx
  image: registry.dinotools.org/docker-ci/python:3.7
  commands:
  - . /opt/python/venv/bin/activate
  - python --version
  - pip install sphinx mock doc8
  - (cd docs/source && sphinx-build -W -b html . ../_build/html)
  - (cd docs/source && sphinx-build -W -b latex . ../_build/latex)
  - doc8 --verbose --allow-long-titles --max-line-length=9999 README.rst CHANGELOG.rst CONTRIBUTING.rst docs/source --ignore-path docs/_build/

---
### Python 3.7
kind: pipeline
name: Python 3.7 - flake8

steps:
- name: test
  image: registry.dinotools.org/docker-ci/python:3.7
  commands:
  - . /opt/python/venv/bin/activate
  - python --version
  - pip install flake8
  - flake8 --ignore F401 src/ssdeep

---
### CentOS 7
kind: pipeline
name: CentOS 7, Python2, builtin

steps:
- name: test
  image: centos:7
  commands:
  - yum -q -y groupinstall "Development Tools"
  - yum -q -y install epel-release
  - |
    yum -q -y install libffi-devel \
      python-devel \
      python-pip \
      pytest \
      automake \
      autoconf \
      libtool
  - BUILD_LIB=1 pip install .
  # - pip install pytest
  - py.test

---
kind: pipeline
name: CentOS 7, Python2, system

steps:
- name: test
  image: centos:7
  commands:
  - yum -q -y groupinstall "Development Tools"
  - yum -q -y install epel-release
  - |
    yum -q -y install libffi-devel \
      libffi-devel \
      python-devel \
      python-pip \
      pytest \
      ssdeep-devel \
      ssdeep-lib
  - BUILD_LIB=0 pip install .
  # - pip install pytest
  - py.test

---
### Debian 8
kind: pipeline
name: Debian 8, Python2, builtin

steps:
- name: test
  image: debian:8
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python python-dev python-pip python-pytest automake autoconf libtool
  - BUILD_LIB=1 pip install .
  # - pip install pytest
  - py.test

---
kind: pipeline
name: Debian 8, Python2, system

steps:
- name: test
  image: debian:8
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python python-dev python-pip python-pytest libfuzzy-dev
  - BUILD_LIB=0 pip install .
  # - pip install pytest
  - py.test

---
kind: pipeline
name: Debian 8, Python3, builtin

steps:
- name: test
  image: debian:8
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python3 python3-dev python3-pip python3-pytest automake autoconf libtool
  - BUILD_LIB=1 pip3 install .
  # - pip3 install pytest
  - py.test-3

---
kind: pipeline
name: Debian 8, Python3, system

steps:
- name: test
  image: debian:8
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python3 python3-dev python3-pip python3-pytest libfuzzy-dev
  - BUILD_LIB=0 pip3 install .
  # - pip3 install pytest
  - py.test-3

---
### Debian 9
kind: pipeline
name: Debian 9, Python2, builtin

steps:
- name: test
  image: debian:9
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python python-dev python-pip python-pytest automake autoconf libtool
  - BUILD_LIB=1 pip install .
  - pip install pytest
  - py.test

---
kind: pipeline
name: Debian 9, Python2, system

steps:
- name: test
  image: debian:9
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python python-dev python-pip python-pytest libfuzzy-dev
  - BUILD_LIB=0 pip install .
  # - pip install pytest
  - py.test

---
kind: pipeline
name: Debian 9, Python3, builtin

steps:
- name: test
  image: debian:9
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python3 python3-dev python3-pip python3-pytest automake autoconf libtool
  - BUILD_LIB=1 pip3 install .
  #- pip3 install pytest
  - py.test-3

---
kind: pipeline
name: Debian 9, Python3, system

steps:
- name: test
  image: debian:9
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python3 python3-dev python3-pip python3-pytest libfuzzy-dev
  - BUILD_LIB=0 pip3 install .
  # - pip3 install pytest
  - py.test-3

---
### Ubuntu 16.04
kind: pipeline
name: Ubuntu 16.04, Python2, builtin

steps:
- name: test
  image: ubuntu:16.04
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python python-dev python-pip python-pytest automake autoconf libtool
  - BUILD_LIB=1 pip install .
  # - pip install pytest
  - py.test

---
kind: pipeline
name: Ubuntu 16.04, Python2, system

steps:
- name: test
  image: ubuntu:16.04
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python python-dev python-pip python-pytest libfuzzy-dev
  - BUILD_LIB=0 pip install .
  # - pip install pytest
  - py.test

---
kind: pipeline
name: Ubuntu 16.04, Python3, builtin

steps:
- name: test
  image: ubuntu:16.04
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python3 python3-dev python3-pip python3-pytest automake autoconf libtool
  - BUILD_LIB=1 pip3 install .
  # - pip3 install pytest
  - py.test-3

---
kind: pipeline
name: Ubuntu 16.04, Python3, system

steps:
- name: test
  image: ubuntu:16.04
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python3 python3-dev python3-pip python3-pytest libfuzzy-dev
  - BUILD_LIB=0 pip3 install .
  # - pip3 install pytest
  - py.test-3

---
### Ubuntu 18.04
kind: pipeline
name: Ubuntu 18.04, Python2, builtin

steps:
- name: test
  image: ubuntu:18.04
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python python-dev python-pip python-pytest automake autoconf libtool
  - BUILD_LIB=1 pip install .
  # - pip install pytest
  - py.test

---
kind: pipeline
name: Ubuntu 18.04, Python2, system

steps:
- name: test
  image: ubuntu:18.04
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python python-dev python-pip python-pytest libfuzzy-dev
  - BUILD_LIB=0 pip install .
  # - pip install pytest
  - py.test

---
kind: pipeline
name: Ubuntu 18.04, Python3, builtin

steps:
- name: test
  image: ubuntu:18.04
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python3 python3-dev python3-pip python3-pytest automake autoconf libtool
  - BUILD_LIB=1 pip3 install .
  # - pip3 install pytest
  - py.test-3

---
kind: pipeline
name: Ubuntu 18.04, Python3, system

steps:
- name: test
  image: ubuntu:18.04
  commands:
  - apt-get update
  - apt-get install -y build-essential libffi-dev python3 python3-dev python3-pip python3-pytest libfuzzy-dev
  - BUILD_LIB=0 pip3 install .
  # - pip3 install pytest
  - py.test-3
