# use container-based infrastructure
sudo: false
language: python
python:
  - "pypy"
  - "pypy3"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - BUILD_LIB=1 pip install .

script: py.test
