# use container-based infrastructure
sudo: false
language: python

matrix:
    include:
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: bionic
        - python: 3.7
          env: TOXENV=docs
          dist: bionic

before_install:
    - if [[ "${TOXENV}" == 'pypy' ]] || [[ "${TOXENV}" == 'pypy3' ]]; then pip install 'setuptools_scm'; fi
    - pip install coveralls

install:
    - pip install tox

script:
    - BUILD_LIB=1 tox --recreate -vvv -e ${TOXENV}

after_success:
    - coveralls --verbose
