# use container-based infrastructure
sudo: false
language: python
python:
  - "pypy"
  - "pypy3"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
  - pip install coveralls

install:
  - BUILD_LIB=1 pip install .
  - pip install pytest coverage

script:
  - coverage run --parallel-mode -m pytest --capture=no --strict tests
  - coverage combine
  - coverage report -m

after_success:
  - coveralls --verbose
