# use container-based infrastructure
sudo: false
language: python

matrix:
    include:
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3
        - python: 2.6
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 3.2
          env: TOXENV=py32
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35

before_install:
    - if [[ "${TOXENV}" == 'py32' ]] || [[ "${TOXENV}" == 'pypy' ]] || [[ "${TOXENV}" == 'pypy3' ]]; then pip install 'setuptools_scm'; fi
    - pip install coveralls

install:
    - pip install tox

script:
    - BUILD_LIB=1 tox --recreate -vvv -e ${TOXENV}

after_success:
    - coveralls --verbose
