name: Python on Debian

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: '10 7 * * 1'

jobs:
  debian_builtin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["debian:10", "debian:11"]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends \
            build-essential \
            libffi-dev \
            python3 \
            python3-dev \
            python3-pip \
            python3-pytest \
            python3-setuptools \
            automake \
            autoconf \
            libtool
      - name: Build
        run: BUILD_LIB=1 pip3 install .
      - name: Test
        run: py.test-3

  debian_system:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["debian:10", "debian:11"]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends \
            build-essential \
            libffi-dev \
            python3 \
            python3-dev \
            python3-pip \
            python3-pytest \
            python3-setuptools \
            libfuzzy-dev
      - name: Build
        run: BUILD_LIB=0 pip3 install .
      - name: Test
        run: py.test-3
